### PR TITLE
python37 compatible

### PR DESCRIPTION
**Pull request by rllin**

### CODE REVIEW

**Review by ananthsub — COMMENTED** [review]
Thanks @rllin for the contribution! Once you sign the CLA, we can merge this in

**Comment by rllin** [comment]
@ananthsub i did sign the CLA.  could you check if i did it wrong?  thanks!

**Comment by ananthsub** [comment]
> @ananthsub i did sign the CLA. could you check if i did it wrong? thanks!

there might be some lag then. From the CI: 

> Once the CLA is signed, our tooling will perform checks and validations. Afterwards, the pull request will be tagged with CLA signed. The tagging process may take up to 1 hour after signing. Please give it that time before contacting us about it.

**Comment by edward-io** [comment]
@rllin thanks for the contribution - I see that you have signed the CLA, so I'll follow up with the OSS team to check why the test is still failing.

**Review by ananthsub — APPROVED** [review]

**Pull request closed without merging**
